[[redirects]]
  from = "/images/thoughtbot-logo-for-readmes.svg"
  to = "https://thoughtbot.com/thoughtbot-logo-for-readmes.svg"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://thoughtbot.com/playbook/our-company/brand"
  status = 301
  force = true
