version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - presskit-bundle-v2-{{ checksum "Gemfile.lock" }}
            - presskit-bundle-v2-

      - run:
          name: Install gem dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: presskit-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build the Middleman site
          command: bin/build

      - run:
          name: Run HTMLProofer
          command: bin/test
